# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(932, -10, 31, 611))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(960, 130, 312, 191))
        self.calendarWidget.setObjectName("calendarWidget")
        self.RainTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.RainTitleLabel.setGeometry(QtCore.QRect(960, 10, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.RainTitleLabel.setFont(font)
        self.RainTitleLabel.setObjectName("RainTitleLabel")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(950, 480, 381, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.SelectDateTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.SelectDateTitleLabel.setGeometry(QtCore.QRect(960, 330, 321, 31))
        self.SelectDateTitleLabel.setObjectName("SelectDateTitleLabel")
        self.modelAccTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.modelAccTitleLabel.setGeometry(QtCore.QRect(960, 370, 141, 91))
        self.modelAccTitleLabel.setObjectName("modelAccTitleLabel")
        self.accuracyLabel = QtWidgets.QLabel(self.centralwidget)
        self.accuracyLabel.setGeometry(QtCore.QRect(1110, 390, 81, 61))
        self.accuracyLabel.setObjectName("accuracyLabel")
        self.prevtimebutton = QtWidgets.QPushButton(self.centralwidget)
        self.prevtimebutton.setGeometry(QtCore.QRect(20, 520, 121, 23))
        self.prevtimebutton.setObjectName("prevtimebutton")
        self.nexttimebutton = QtWidgets.QPushButton(self.centralwidget)
        self.nexttimebutton.setGeometry(QtCore.QRect(150, 520, 121, 23))
        self.nexttimebutton.setObjectName("nexttimebutton")
        self.currentbutton = QtWidgets.QPushButton(self.centralwidget)
        self.currentbutton.setGeometry(QtCore.QRect(280, 520, 101, 23))
        self.currentbutton.setObjectName("currentbutton")
        self.graphwidget = PlotWidget(self.centralwidget)
        self.graphwidget.setGeometry(QtCore.QRect(10, 10, 921, 491))
        self.graphwidget.setObjectName("widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        self.menuCustom_Construction_Weather = QtWidgets.QMenu(self.menubar)
        self.menuCustom_Construction_Weather.setObjectName("menuCustom_Construction_Weather")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCustom_Construction_Weather.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RainTitleLabel.setText(_translate("MainWindow", "Will it rain today?"))
        self.SelectDateTitleLabel.setText(
            _translate("MainWindow", "Select a date in the past to compare predicted vs. realized results."))
        self.modelAccTitleLabel.setText(_translate("MainWindow", "Current Model Accuracy:"))
        self.accuracyLabel.setText(_translate("MainWindow", "XX%"))
        self.prevtimebutton.setText(_translate("MainWindow", "Previous Timespan"))
        self.nexttimebutton.setText(_translate("MainWindow", "Next Timespan"))
        self.currentbutton.setText(_translate("MainWindow", "Current Timespan"))
        self.menuCustom_Construction_Weather.setTitle(_translate("MainWindow", "Custom Construction Weather"))


from pyqtgraph import PlotWidget
